# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitoring.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 742)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("battery.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Header = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.Header)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.COMBox = QtWidgets.QComboBox(self.Header)
        self.COMBox.setMinimumSize(QtCore.QSize(150, 0))
        self.COMBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.COMBox.setObjectName("COMBox")
        self.horizontalLayout.addWidget(self.COMBox)
        self.refresh = QtWidgets.QPushButton(self.Header)
        self.refresh.setMaximumSize(QtCore.QSize(20, 20))
        self.refresh.setStyleSheet("background: transparent")
        self.refresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/refresh/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon1)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout.addWidget(self.refresh)
        self.portbtn = QtWidgets.QPushButton(self.Header)
        self.portbtn.setMinimumSize(QtCore.QSize(0, 20))
        self.portbtn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.portbtn.setObjectName("portbtn")
        self.horizontalLayout.addWidget(self.portbtn)
        self.portclosebtn = QtWidgets.QPushButton(self.Header)
        self.portclosebtn.setEnabled(False)
        self.portclosebtn.setMinimumSize(QtCore.QSize(75, 20))
        self.portclosebtn.setMaximumSize(QtCore.QSize(75, 20))
        self.portclosebtn.setObjectName("portclosebtn")
        self.horizontalLayout.addWidget(self.portclosebtn)
        self.port_alarm = QtWidgets.QLabel(self.Header)
        self.port_alarm.setMinimumSize(QtCore.QSize(20, 20))
        self.port_alarm.setMaximumSize(QtCore.QSize(20, 20))
        self.port_alarm.setText("")
        self.port_alarm.setObjectName("port_alarm")
        self.horizontalLayout.addWidget(self.port_alarm)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.Header, 0, 0, 1, 1)
        self.Body = QtWidgets.QFrame(self.centralwidget)
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.frame_3 = QtWidgets.QFrame(self.Body)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.stationname = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stationname.setFont(font)
        self.stationname.setText("")
        self.stationname.setObjectName("stationname")
        self.horizontalLayout_16.addWidget(self.stationname)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.Body)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.timelabel = QtWidgets.QLabel(self.frame_2)
        self.timelabel.setText("")
        self.timelabel.setObjectName("timelabel")
        self.horizontalLayout_15.addWidget(self.timelabel)
        self.verticalLayout.addWidget(self.frame_2)
        self.info = QtWidgets.QFrame(self.Body)
        self.info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info.setObjectName("info")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.info)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ch = QtWidgets.QLabel(self.info)
        self.ch.setObjectName("ch")
        self.horizontalLayout_2.addWidget(self.ch)
        self.voltage = QtWidgets.QLabel(self.info)
        self.voltage.setObjectName("voltage")
        self.horizontalLayout_2.addWidget(self.voltage)
        self.status = QtWidgets.QLabel(self.info)
        self.status.setMinimumSize(QtCore.QSize(80, 0))
        self.status.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status.setObjectName("status")
        self.horizontalLayout_2.addWidget(self.status)
        self.empty = QtWidgets.QLabel(self.info)
        self.empty.setMinimumSize(QtCore.QSize(15, 15))
        self.empty.setMaximumSize(QtCore.QSize(15, 15))
        self.empty.setText("")
        self.empty.setObjectName("empty")
        self.horizontalLayout_2.addWidget(self.empty)
        self.verticalLayout.addWidget(self.info)
        self.ch1 = QtWidgets.QFrame(self.Body)
        self.ch1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch1.setObjectName("ch1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ch1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ch_1 = QtWidgets.QLabel(self.ch1)
        self.ch_1.setObjectName("ch_1")
        self.horizontalLayout_3.addWidget(self.ch_1)
        self.voltage_1 = QtWidgets.QLabel(self.ch1)
        self.voltage_1.setText("")
        self.voltage_1.setObjectName("voltage_1")
        self.horizontalLayout_3.addWidget(self.voltage_1)
        self.status_1 = QtWidgets.QLabel(self.ch1)
        self.status_1.setMinimumSize(QtCore.QSize(80, 0))
        self.status_1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_1.setText("")
        self.status_1.setObjectName("status_1")
        self.horizontalLayout_3.addWidget(self.status_1)
        self.light_1 = QtWidgets.QLabel(self.ch1)
        self.light_1.setMinimumSize(QtCore.QSize(15, 15))
        self.light_1.setMaximumSize(QtCore.QSize(15, 15))
        self.light_1.setStyleSheet("")
        self.light_1.setText("")
        self.light_1.setObjectName("light_1")
        self.horizontalLayout_3.addWidget(self.light_1)
        self.verticalLayout.addWidget(self.ch1)
        self.ch2 = QtWidgets.QFrame(self.Body)
        self.ch2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch2.setObjectName("ch2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ch2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ch_2 = QtWidgets.QLabel(self.ch2)
        self.ch_2.setObjectName("ch_2")
        self.horizontalLayout_4.addWidget(self.ch_2)
        self.voltage_2 = QtWidgets.QLabel(self.ch2)
        self.voltage_2.setText("")
        self.voltage_2.setObjectName("voltage_2")
        self.horizontalLayout_4.addWidget(self.voltage_2)
        self.status_2 = QtWidgets.QLabel(self.ch2)
        self.status_2.setMinimumSize(QtCore.QSize(80, 0))
        self.status_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_2.setText("")
        self.status_2.setObjectName("status_2")
        self.horizontalLayout_4.addWidget(self.status_2)
        self.light_2 = QtWidgets.QLabel(self.ch2)
        self.light_2.setMinimumSize(QtCore.QSize(15, 15))
        self.light_2.setMaximumSize(QtCore.QSize(15, 15))
        self.light_2.setStyleSheet("")
        self.light_2.setText("")
        self.light_2.setObjectName("light_2")
        self.horizontalLayout_4.addWidget(self.light_2)
        self.verticalLayout.addWidget(self.ch2)
        self.ch3 = QtWidgets.QFrame(self.Body)
        self.ch3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch3.setObjectName("ch3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ch3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ch_3 = QtWidgets.QLabel(self.ch3)
        self.ch_3.setObjectName("ch_3")
        self.horizontalLayout_5.addWidget(self.ch_3)
        self.voltage_3 = QtWidgets.QLabel(self.ch3)
        self.voltage_3.setText("")
        self.voltage_3.setObjectName("voltage_3")
        self.horizontalLayout_5.addWidget(self.voltage_3)
        self.status_3 = QtWidgets.QLabel(self.ch3)
        self.status_3.setMinimumSize(QtCore.QSize(80, 0))
        self.status_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_3.setText("")
        self.status_3.setObjectName("status_3")
        self.horizontalLayout_5.addWidget(self.status_3)
        self.light_3 = QtWidgets.QLabel(self.ch3)
        self.light_3.setMinimumSize(QtCore.QSize(15, 15))
        self.light_3.setMaximumSize(QtCore.QSize(15, 15))
        self.light_3.setStyleSheet("")
        self.light_3.setText("")
        self.light_3.setObjectName("light_3")
        self.horizontalLayout_5.addWidget(self.light_3)
        self.verticalLayout.addWidget(self.ch3)
        self.ch4 = QtWidgets.QFrame(self.Body)
        self.ch4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch4.setObjectName("ch4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ch4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ch_4 = QtWidgets.QLabel(self.ch4)
        self.ch_4.setObjectName("ch_4")
        self.horizontalLayout_8.addWidget(self.ch_4)
        self.voltage_4 = QtWidgets.QLabel(self.ch4)
        self.voltage_4.setText("")
        self.voltage_4.setObjectName("voltage_4")
        self.horizontalLayout_8.addWidget(self.voltage_4)
        self.status_4 = QtWidgets.QLabel(self.ch4)
        self.status_4.setMinimumSize(QtCore.QSize(80, 0))
        self.status_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_4.setText("")
        self.status_4.setObjectName("status_4")
        self.horizontalLayout_8.addWidget(self.status_4)
        self.light_4 = QtWidgets.QLabel(self.ch4)
        self.light_4.setMinimumSize(QtCore.QSize(15, 15))
        self.light_4.setMaximumSize(QtCore.QSize(15, 15))
        self.light_4.setStyleSheet("")
        self.light_4.setText("")
        self.light_4.setObjectName("light_4")
        self.horizontalLayout_8.addWidget(self.light_4)
        self.verticalLayout.addWidget(self.ch4)
        self.ch5 = QtWidgets.QFrame(self.Body)
        self.ch5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch5.setObjectName("ch5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ch5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ch_5 = QtWidgets.QLabel(self.ch5)
        self.ch_5.setObjectName("ch_5")
        self.horizontalLayout_6.addWidget(self.ch_5)
        self.voltage_5 = QtWidgets.QLabel(self.ch5)
        self.voltage_5.setText("")
        self.voltage_5.setObjectName("voltage_5")
        self.horizontalLayout_6.addWidget(self.voltage_5)
        self.status_5 = QtWidgets.QLabel(self.ch5)
        self.status_5.setMinimumSize(QtCore.QSize(80, 0))
        self.status_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_5.setText("")
        self.status_5.setObjectName("status_5")
        self.horizontalLayout_6.addWidget(self.status_5)
        self.light_5 = QtWidgets.QLabel(self.ch5)
        self.light_5.setMinimumSize(QtCore.QSize(15, 15))
        self.light_5.setMaximumSize(QtCore.QSize(15, 15))
        self.light_5.setStyleSheet("")
        self.light_5.setText("")
        self.light_5.setObjectName("light_5")
        self.horizontalLayout_6.addWidget(self.light_5)
        self.verticalLayout.addWidget(self.ch5)
        self.ch6 = QtWidgets.QFrame(self.Body)
        self.ch6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch6.setObjectName("ch6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ch6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ch_6 = QtWidgets.QLabel(self.ch6)
        self.ch_6.setObjectName("ch_6")
        self.horizontalLayout_7.addWidget(self.ch_6)
        self.voltage_6 = QtWidgets.QLabel(self.ch6)
        self.voltage_6.setText("")
        self.voltage_6.setObjectName("voltage_6")
        self.horizontalLayout_7.addWidget(self.voltage_6)
        self.status_6 = QtWidgets.QLabel(self.ch6)
        self.status_6.setMinimumSize(QtCore.QSize(80, 0))
        self.status_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_6.setText("")
        self.status_6.setObjectName("status_6")
        self.horizontalLayout_7.addWidget(self.status_6)
        self.light_6 = QtWidgets.QLabel(self.ch6)
        self.light_6.setMinimumSize(QtCore.QSize(15, 15))
        self.light_6.setMaximumSize(QtCore.QSize(15, 15))
        self.light_6.setStyleSheet("")
        self.light_6.setText("")
        self.light_6.setObjectName("light_6")
        self.horizontalLayout_7.addWidget(self.light_6)
        self.verticalLayout.addWidget(self.ch6)
        self.ch7 = QtWidgets.QFrame(self.Body)
        self.ch7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch7.setObjectName("ch7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.ch7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ch_7 = QtWidgets.QLabel(self.ch7)
        self.ch_7.setObjectName("ch_7")
        self.horizontalLayout_9.addWidget(self.ch_7)
        self.voltage_7 = QtWidgets.QLabel(self.ch7)
        self.voltage_7.setText("")
        self.voltage_7.setObjectName("voltage_7")
        self.horizontalLayout_9.addWidget(self.voltage_7)
        self.status_7 = QtWidgets.QLabel(self.ch7)
        self.status_7.setMinimumSize(QtCore.QSize(80, 0))
        self.status_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_7.setText("")
        self.status_7.setObjectName("status_7")
        self.horizontalLayout_9.addWidget(self.status_7)
        self.light_7 = QtWidgets.QLabel(self.ch7)
        self.light_7.setMinimumSize(QtCore.QSize(15, 15))
        self.light_7.setMaximumSize(QtCore.QSize(15, 15))
        self.light_7.setStyleSheet("")
        self.light_7.setText("")
        self.light_7.setObjectName("light_7")
        self.horizontalLayout_9.addWidget(self.light_7)
        self.verticalLayout.addWidget(self.ch7)
        self.ch8 = QtWidgets.QFrame(self.Body)
        self.ch8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch8.setObjectName("ch8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ch8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ch_8 = QtWidgets.QLabel(self.ch8)
        self.ch_8.setObjectName("ch_8")
        self.horizontalLayout_10.addWidget(self.ch_8)
        self.voltage_8 = QtWidgets.QLabel(self.ch8)
        self.voltage_8.setText("")
        self.voltage_8.setObjectName("voltage_8")
        self.horizontalLayout_10.addWidget(self.voltage_8)
        self.status_8 = QtWidgets.QLabel(self.ch8)
        self.status_8.setMinimumSize(QtCore.QSize(80, 0))
        self.status_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_8.setText("")
        self.status_8.setObjectName("status_8")
        self.horizontalLayout_10.addWidget(self.status_8)
        self.light_8 = QtWidgets.QLabel(self.ch8)
        self.light_8.setMinimumSize(QtCore.QSize(15, 15))
        self.light_8.setMaximumSize(QtCore.QSize(15, 15))
        self.light_8.setStyleSheet("")
        self.light_8.setText("")
        self.light_8.setObjectName("light_8")
        self.horizontalLayout_10.addWidget(self.light_8)
        self.verticalLayout.addWidget(self.ch8)
        self.ch9 = QtWidgets.QFrame(self.Body)
        self.ch9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch9.setObjectName("ch9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.ch9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ch_9 = QtWidgets.QLabel(self.ch9)
        self.ch_9.setObjectName("ch_9")
        self.horizontalLayout_13.addWidget(self.ch_9)
        self.voltage_9 = QtWidgets.QLabel(self.ch9)
        self.voltage_9.setText("")
        self.voltage_9.setObjectName("voltage_9")
        self.horizontalLayout_13.addWidget(self.voltage_9)
        self.status_9 = QtWidgets.QLabel(self.ch9)
        self.status_9.setMinimumSize(QtCore.QSize(80, 0))
        self.status_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_9.setText("")
        self.status_9.setObjectName("status_9")
        self.horizontalLayout_13.addWidget(self.status_9)
        self.light_9 = QtWidgets.QLabel(self.ch9)
        self.light_9.setMinimumSize(QtCore.QSize(15, 15))
        self.light_9.setMaximumSize(QtCore.QSize(15, 15))
        self.light_9.setStyleSheet("")
        self.light_9.setText("")
        self.light_9.setObjectName("light_9")
        self.horizontalLayout_13.addWidget(self.light_9)
        self.verticalLayout.addWidget(self.ch9)
        self.ch10 = QtWidgets.QFrame(self.Body)
        self.ch10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch10.setObjectName("ch10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ch10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ch_10 = QtWidgets.QLabel(self.ch10)
        self.ch_10.setObjectName("ch_10")
        self.horizontalLayout_12.addWidget(self.ch_10)
        self.voltage_10 = QtWidgets.QLabel(self.ch10)
        self.voltage_10.setText("")
        self.voltage_10.setObjectName("voltage_10")
        self.horizontalLayout_12.addWidget(self.voltage_10)
        self.status_10 = QtWidgets.QLabel(self.ch10)
        self.status_10.setMinimumSize(QtCore.QSize(80, 0))
        self.status_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_10.setText("")
        self.status_10.setObjectName("status_10")
        self.horizontalLayout_12.addWidget(self.status_10)
        self.light_10 = QtWidgets.QLabel(self.ch10)
        self.light_10.setMinimumSize(QtCore.QSize(15, 15))
        self.light_10.setMaximumSize(QtCore.QSize(15, 15))
        self.light_10.setStyleSheet("")
        self.light_10.setText("")
        self.light_10.setObjectName("light_10")
        self.horizontalLayout_12.addWidget(self.light_10)
        self.verticalLayout.addWidget(self.ch10)
        self.ch11 = QtWidgets.QFrame(self.Body)
        self.ch11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ch11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ch11.setObjectName("ch11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.ch11)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ch_11 = QtWidgets.QLabel(self.ch11)
        self.ch_11.setObjectName("ch_11")
        self.horizontalLayout_11.addWidget(self.ch_11)
        self.voltage_11 = QtWidgets.QLabel(self.ch11)
        self.voltage_11.setText("")
        self.voltage_11.setObjectName("voltage_11")
        self.horizontalLayout_11.addWidget(self.voltage_11)
        self.status_11 = QtWidgets.QLabel(self.ch11)
        self.status_11.setMinimumSize(QtCore.QSize(80, 0))
        self.status_11.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_11.setText("")
        self.status_11.setObjectName("status_11")
        self.horizontalLayout_11.addWidget(self.status_11)
        self.light_11 = QtWidgets.QLabel(self.ch11)
        self.light_11.setMinimumSize(QtCore.QSize(15, 15))
        self.light_11.setMaximumSize(QtCore.QSize(15, 15))
        self.light_11.setStyleSheet("")
        self.light_11.setText("")
        self.light_11.setObjectName("light_11")
        self.horizontalLayout_11.addWidget(self.light_11)
        self.verticalLayout.addWidget(self.ch11)
        self.gridLayout.addWidget(self.Body, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Station = QtWidgets.QLabel(self.frame)
        self.Station.setEnabled(True)
        self.Station.setMinimumSize(QtCore.QSize(50, 0))
        self.Station.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Station.setObjectName("Station")
        self.horizontalLayout_14.addWidget(self.Station)
        self.StationBox = QtWidgets.QComboBox(self.frame)
        self.StationBox.setEnabled(True)
        self.StationBox.setMinimumSize(QtCore.QSize(150, 0))
        self.StationBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.StationBox.setObjectName("StationBox")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.StationBox.addItem("")
        self.horizontalLayout_14.addWidget(self.StationBox)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(20, 20))
        self.label_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.connectbtn = QtWidgets.QPushButton(self.frame)
        self.connectbtn.setEnabled(False)
        self.connectbtn.setMinimumSize(QtCore.QSize(75, 20))
        self.connectbtn.setMaximumSize(QtCore.QSize(75, 20))
        self.connectbtn.setObjectName("connectbtn")
        self.horizontalLayout_14.addWidget(self.connectbtn)
        self.Stopbtn = QtWidgets.QPushButton(self.frame)
        self.Stopbtn.setEnabled(False)
        self.Stopbtn.setMinimumSize(QtCore.QSize(75, 20))
        self.Stopbtn.setMaximumSize(QtCore.QSize(75, 20))
        self.Stopbtn.setObjectName("Stopbtn")
        self.horizontalLayout_14.addWidget(self.Stopbtn)
        self.station_alarm = QtWidgets.QLabel(self.frame)
        self.station_alarm.setMinimumSize(QtCore.QSize(20, 20))
        self.station_alarm.setMaximumSize(QtCore.QSize(20, 20))
        self.station_alarm.setText("")
        self.station_alarm.setObjectName("station_alarm")
        self.horizontalLayout_14.addWidget(self.station_alarm)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "충전제어기 모니터링"))
        self.label.setText(_translate("MainWindow", "PORT "))
        self.portbtn.setText(_translate("MainWindow", "열기"))
        self.portclosebtn.setText(_translate("MainWindow", "닫기"))
        self.label_2.setText(_translate("MainWindow", "최근수신시간"))
        self.ch.setText(_translate("MainWindow", "채널"))
        self.voltage.setText(_translate("MainWindow", "전압"))
        self.status.setText(_translate("MainWindow", "상태"))
        self.ch_1.setText(_translate("MainWindow", "CH1"))
        self.ch_2.setText(_translate("MainWindow", "CH2"))
        self.ch_3.setText(_translate("MainWindow", "CH3"))
        self.ch_4.setText(_translate("MainWindow", "CH4"))
        self.ch_5.setText(_translate("MainWindow", "CH5"))
        self.ch_6.setText(_translate("MainWindow", "CH6"))
        self.ch_7.setText(_translate("MainWindow", "CH7"))
        self.ch_8.setText(_translate("MainWindow", "CH8"))
        self.ch_9.setText(_translate("MainWindow", "CH9"))
        self.ch_10.setText(_translate("MainWindow", "CH10"))
        self.ch_11.setText(_translate("MainWindow", "CH11"))
        self.Station.setText(_translate("MainWindow", "Station"))
        self.StationBox.setItemText(0, _translate("MainWindow", "00"))
        self.StationBox.setItemText(1, _translate("MainWindow", "01"))
        self.StationBox.setItemText(2, _translate("MainWindow", "02"))
        self.StationBox.setItemText(3, _translate("MainWindow", "03"))
        self.StationBox.setItemText(4, _translate("MainWindow", "04"))
        self.StationBox.setItemText(5, _translate("MainWindow", "05"))
        self.StationBox.setItemText(6, _translate("MainWindow", "06"))
        self.StationBox.setItemText(7, _translate("MainWindow", "07"))
        self.StationBox.setItemText(8, _translate("MainWindow", "08"))
        self.StationBox.setItemText(9, _translate("MainWindow", "09"))
        self.StationBox.setItemText(10, _translate("MainWindow", "10"))
        self.StationBox.setItemText(11, _translate("MainWindow", "11"))
        self.StationBox.setItemText(12, _translate("MainWindow", "12"))
        self.StationBox.setItemText(13, _translate("MainWindow", "13"))
        self.StationBox.setItemText(14, _translate("MainWindow", "14"))
        self.StationBox.setItemText(15, _translate("MainWindow", "15"))
        self.connectbtn.setText(_translate("MainWindow", "Connect"))
        self.Stopbtn.setText(_translate("MainWindow", "Stop"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

